[package]
name = "palsav-decoder"
description = "Shared Palworld save decoding contracts and implementation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
flate2.workspace = true
oozextract.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
